name: Docker Build and Push on Tag

on:
  push:
    tags:
      - '*'  # Триггер на любой тег

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Extract tag name
      id: get_tag
      run: echo "::set-output name=TAG::${GITHUB_REF#refs/tags/}"
      # Этот шаг просто извлекает имя тега Git

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dora4github:${{ steps.get_tag.outputs.TAG }}
        # Использование извлеченного тега для тегирования Docker образа
